#!/bin/sh
# Output of :
# code --list-extensions | xargs -L 1 echo code --install-extension

code --install-extension alefragnani.project-manager
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension Angular.ng-template
code --install-extension Arjun.swagger-viewer
code --install-extension atlassian.atlascode
code --install-extension Azurite.azurite
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension foxundermoon.shell-format
code --install-extension GitLab.gitlab-workflow
code --install-extension golang.go
code --install-extension gregoire.dance
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension influxdata.flux
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurefunctions
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-ossdata.vscode-postgresql
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension myxvisual.vscode-ts-uml
code --install-extension NicolasVuillamy.vscode-groovy-lint
code --install-extension nrwl.angular-console
code --install-extension octref.vetur
code --install-extension Orta.vscode-jest
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ryu1kn.partial-diff
code --install-extension silvenon.mdx
code --install-extension skyapps.fish-vscode
code --install-extension SonarSource.sonarlint-vscode
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-french
code --install-extension sumneko.lua
code --install-extension tfsec.tfsec
code --install-extension timonwong.shellcheck
code --install-extension twxs.cmake
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vsciot-vscode.azure-iot-edge
code --install-extension vsciot-vscode.azure-iot-toolkit
code --install-extension vsciot-vscode.azure-iot-tools
code --install-extension vsciot-vscode.vscode-iot-device-cube
code --install-extension vsciot-vscode.vscode-iot-workbench
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
code --install-extension wix.vscode-import-cost
code --install-extension zxh404.vscode-proto3
