#!/bin/sh

ORIG_MSG_FILE="$1"
TEMP="$(mktemp /tmp/git-XXXXX)"

USER_NAME="$(git config --get user.name)"
USER_EMAIL="$(git config --get user.email)"

(echo "# User: $USER_NAME ($USER_EMAIL)"; cat "$ORIG_MSG_FILE") > "$TEMP"
cat "$TEMP" > "$ORIG_MSG_FILE"
